[connections.snowflake]
account = "AQJBWMB-OJB91426"
user = "MariaValeroGonzalez"
password = "PushGaming_02062025"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
